include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - comment_references
    - unnecessary_lambdas
    - avoid_returning_this
    - avoid_returning_null
    - prefer_mixin
    - avoid_equals_and_hash_code_on_mutable_classes
    - unnecessary_statements
    - cancel_subscriptions
    - prefer_final_locals
    - prefer_asserts_in_initializer_lists
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unsafe_html
    - close_sinks